### ISSUE TITLE
Write it in new file

### ISSUE THREAD

**Issue by NoorAhmd** [madnight/ndjson-to-json#4]
I think it would have been great to write a new file after conversion. I can take care of it if you wish

**Comment by madnight** [comment]
Sure, a PR is welcome.

**Comment by madnight** [comment]
I just had a second thought and I think: ```ndjson-to-json file.json > new_file.json``` is very easy syntax and the print to stdout allows for easy chaining with other tools like `ndjson-to-json file.json | jq ...`. However, I would accept a PR that allow you to define a optional param like (--output/-o) ```ndjson-to-json -o new_file.json file.json```.

**Comment by NoorAhmd** [comment]
Sure. Thats great thought

**Comment by madnight** [comment]
I added the -o filename option as per our discussion.
